title: "منبع مطلق حقیقت | Absolute Truth Nexus"
description: "مرجع کیهانی برای عمیق‌ترین مفاهیم علم، هنر و تکنولوژی"
url: "https://honardehkadeh807-netizen.github.io" 
baseurl: "/akashic-nexus" 
theme: jekyll-theme-hacker 
permalink: /:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
